## YAML Template.
---

debug: true

logging:
    level:
        root: WARN
        org.springframework: WARN
        org.springframework.web: WARN
        org.springframework.boot: OFF
        org.hibernate: OFF
        org.hibernate.SQL : OFF
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: WARN
        com.ap: WARN
        
spring:
    profiles:
        active: prod
        
    datasource:
      driver-class-name: org.postgresql.ds.PGSimpleDataSource
      url: test
      poolName: SpringBootHikariCP
      username: postgres
      password: admin  
      
    jpa:
        show_sql: false  
        hibernate:
            #ddl-auto: validate
            ddl-auto: create
        
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false                       
        
    mail:
        host: localhost
        port: 25
        username:
        password:
        
    rabbitmq:
        hostname: localhost
        username: guest
        password: guest
        
    data:
        mongodb:
            uri: mongodb://localhost:27017
            
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: 103.44.27.76:9300
            cluster-port: 9300
            cluster-host: 103.44.27.76

server:
    port: 9000
    compression:
        enabled: false
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json 
        
        
ctm:        
    mail:
        from: development@localhost  
        
    security:
        authentication:
            Jwt.secret: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxD6QynJJcnjNtzkBV+8NjFUQOp6gk6iWoKpfV7Yy2GoEcoyv7k02LtJG70z9CGwjAobwjtXcAu+BzxtmI592fjW1H0HKuVOSPhVEq0uZKOOI6A3SsJEr8E0NNASDtwvJVELyrqO/UBdefhY1lKwsEJAIQABkKBABOs2wVkglDiY5PhfGkf2vuLBnwDWIG217Eh7o4SWPyR567x9sCORf6cOE6glbpGnE4Y43n5IPZZBkXyH/kXEm0GWohBJ3RI8st2Gae8RIs/91c0m3/wUqiXF9zlmcbayKQTOUqUCuRkd3AwSBPBPCMzRAVIZ4qHXmOwgLp2oAlZKO7wnhH8HbYwIDAQAB-----END PUBLIC KEY-----
                  
        
    datasource: 
        serverName: localhost
        portNumber: 5432
        databaseName: postgres
        
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: ap            
        logs: # report metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
            
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
        